document.body.onload=function(){
    nbr=2;
    p=0;
    container=document.getElementById("container");
    g=document.getElementById("g");
    d=document.getElementById("d");
    container.style.width=(1000*nbr)+"px";
    for(i=1;i<=nbr;i++){
       div=document.createElement("div");
       div.className="slide";
       div.style.backgroundImage="url('media/im"+i+".png')";
       container.appendChild(div);
    };
    afficherMasquer();
 };
 g.onclick=function(){
    if(p<0)
       p++;
    container.style.transform="translate("+p*1000+"px)";
    container.style.transition="all 0.5s ease";
    afficherMasquer();
 };
 d.onclick=function(){
    if(p>-nbr+1)
       p--;
    container.style.transform="translate("+p*1000+"px)";
    container.style.transition="all 0.5s ease";
    afficherMasquer();
 };
 function afficherMasquer() {
    if(p==-nbr+1)
       d.style.visibility="hidden";
    else
       d.style.visibility="visible";
    if(p==0)
       g.style.visibility="hidden";
    else
       g.style.visibility="visible";
 }